pipeline {
    agent any
    
    parameters{
	  string(name:'version',defaultValue:'1.0.0', description:'The version of artifact')
	  booleanParam(name:'promote',defaultValue: false, description:'Publish new version')
    }

    stages {
        stage('Clone'){
            steps {
                echo 'Cloning.. And setting up voulumes..'
                sh 'docker system prune --all --volumes -f'
                sh 'docker volume create vol-in'
                sh 'docker volume create vol-out'
                sh 'docker build -t cloner:latest . -f /var/jenkins_home/workspace/DevOpsPipeline2/docker-clone'
                sh 'docker run --mount source=vol-in,destination=/inputVol cloner:latest'
            }

        }

        stage('Build') {
            steps {
                echo 'Building..'
                sh 'docker build -t builder:latest . -f /var/jenkins_home/workspace/DevOpsPipeline2/docker-build'
                sh 'docker run --mount source=vol-in,destination=/inputVol --mount source=vol-out,destination=/outputVol builder:latest'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
		echo 'Deploying..'
            }
        }
        stage('Publish') {
            steps {
                echo 'Publishing..'
            }
        }
    }
}
