import React, {FunctionComponent} from 'react'
import classes from "../css/app.module.css";
import { CategoriesBar } from './CategoriesBar';
//import classesSpefic from "../css/about.module.css";
import { PathBar } from './PathBar';

interface linkList{
    name: string,
    url: string
}

interface Props{
}

export const About: FunctionComponent<Props>=(props: Props)=>{
    const pathList : linkList[] = [{"name": "Bastim", "url": "/"}, {"name": "About", "url": "/about"} ];


    return(
        <div className={classes.page}>
           <PathBar pathList={pathList}/>
           
           <div className={classes["content"]}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam aliquet lacus at neque interdum malesuada. Sed finibus vestibulum velit, in semper arcu vehicula eget. Nunc tincidunt nunc risus, id volutpat sem lobortis vel. Maecenas facilisis leo et faucibus viverra. Nulla commodo nulla velit, eget eleifend ipsum vehicula a. Morbi mattis vitae nibh ut vulputate. Vestibulum blandit ullamcorper felis, at condimentum purus rutrum quis. Suspendisse semper, lacus et efficitur varius, lectus enim tincidunt nisl, a tempor massa ex sed odio. Sed id maximus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; <br/>

Sed mollis lectus nec sapien cursus, vel pharetra magna imperdiet. Ut egestas vel turpis id congue. Donec ornare aliquam erat, sit amet suscipit elit. Fusce auctor mi lacinia luctus auctor. Suspendisse elementum ipsum ut nunc fermentum, et luctus ex iaculis. Integer quis hendrerit massa, sollicitudin dictum nisi. Sed in nisi iaculis, mollis justo a, tincidunt libero. In id nunc ac mi vulputate porttitor nec condimentum ex. Mauris mattis convallis augue et semper. Aliquam blandit facilisis mi eget accumsan. Morbi fermentum facilisis dui, vitae sagittis neque gravida nec. Fusce facilisis tellus sagittis pulvinar iaculis. Nam vulputate, tellus vitae consectetur bibendum, leo lorem varius lectus, sit amet egestas nunc est ac dui. Donec lacus tortor, vestibulum et laoreet laoreet, dictum nec sapien. Nam mi eros, pharetra ut arcu sed, ornare iaculis elit.<br/>

Mauris porta felis vel eros condimentum posuere. Nulla eleifend luctus dolor a maximus. Proin vulputate tortor tellus, a molestie turpis laoreet at. Duis id nunc ante. Curabitur mollis placerat lacus et finibus. Nunc porttitor fringilla dolor id laoreet. Sed mauris tortor, condimentum at lorem in, faucibus efficitur dolor.<br/>

Aenean auctor nisi scelerisque tellus tincidunt aliquet. In faucibus metus nec ultricies condimentum. Sed tincidunt risus nibh, sed aliquam ex pretium ut. Integer blandit metus at dui ultricies, ut facilisis libero facilisis. Nam sagittis varius pellentesque. Morbi sagittis lacus ac sollicitudin rutrum. Vivamus leo massa, placerat ut tortor in, molestie condimentum elit. Vivamus rhoncus felis non pharetra molestie. Cras sodales dictum dapibus.<br/>

In euismod vestibulum quam, ut ultrices magna porttitor in. Fusce vitae luctus mi, ac varius velit. In bibendum, nunc maximus condimentum maximus, magna mi eleifend massa, sagittis rhoncus purus turpis quis ipsum. Donec consectetur feugiat risus. Proin nibh augue, facilisis at nulla ut, fermentum cursus dolor. Mauris vel interdum lacus. In ut tellus odio. Aliquam mattis mi at nisl elementum consequat. Sed odio purus, imperdiet sit amet enim nec, pretium mollis tellus. Pellentesque vitae tincidunt sapien. Curabitur faucibus euismod nibh, vitae elementum elit malesuada quis. Etiam ut turpis vel dui varius dapibus. Duis at tempus nisi, sit amet luctus orci. Integer porta sapien at purus mattis tempus. Aenean sagittis libero nisi, pharetra consectetur sem hendrerit sit amet.<br/> 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam aliquet lacus at neque interdum malesuada. Sed finibus vestibulum velit, in semper arcu vehicula eget. Nunc tincidunt nunc risus, id volutpat sem lobortis vel. Maecenas facilisis leo et faucibus viverra. Nulla commodo nulla velit, eget eleifend ipsum vehicula a. Morbi mattis vitae nibh ut vulputate. Vestibulum blandit ullamcorper felis, at condimentum purus rutrum quis. Suspendisse semper, lacus et efficitur varius, lectus enim tincidunt nisl, a tempor massa ex sed odio. Sed id maximus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; <br/>

Sed mollis lectus nec sapien cursus, vel pharetra magna imperdiet. Ut egestas vel turpis id congue. Donec ornare aliquam erat, sit amet suscipit elit. Fusce auctor mi lacinia luctus auctor. Suspendisse elementum ipsum ut nunc fermentum, et luctus ex iaculis. Integer quis hendrerit massa, sollicitudin dictum nisi. Sed in nisi iaculis, mollis justo a, tincidunt libero. In id nunc ac mi vulputate porttitor nec condimentum ex. Mauris mattis convallis augue et semper. Aliquam blandit facilisis mi eget accumsan. Morbi fermentum facilisis dui, vitae sagittis neque gravida nec. Fusce facilisis tellus sagittis pulvinar iaculis. Nam vulputate, tellus vitae consectetur bibendum, leo lorem varius lectus, sit amet egestas nunc est ac dui. Donec lacus tortor, vestibulum et laoreet laoreet, dictum nec sapien. Nam mi eros, pharetra ut arcu sed, ornare iaculis elit.<br/>

Mauris porta felis vel eros condimentum posuere. Nulla eleifend luctus dolor a maximus. Proin vulputate tortor tellus, a molestie turpis laoreet at. Duis id nunc ante. Curabitur mollis placerat lacus et finibus. Nunc porttitor fringilla dolor id laoreet. Sed mauris tortor, condimentum at lorem in, faucibus efficitur dolor.<br/>

Aenean auctor nisi scelerisque tellus tincidunt aliquet. In faucibus metus nec ultricies condimentum. Sed tincidunt risus nibh, sed aliquam ex pretium ut. Integer blandit metus at dui ultricies, ut facilisis libero facilisis. Nam sagittis varius pellentesque. Morbi sagittis lacus ac sollicitudin rutrum. Vivamus leo massa, placerat ut tortor in, molestie condimentum elit. Vivamus rhoncus felis non pharetra molestie. Cras sodales dictum dapibus.<br/>

In euismod vestibulum quam, ut ultrices magna porttitor in. Fusce vitae luctus mi, ac varius velit. In bibendum, nunc maximus condimentum maximus, magna mi eleifend massa, sagittis rhoncus purus turpis quis ipsum. Donec consectetur feugiat risus. Proin nibh augue, facilisis at nulla ut, fermentum cursus dolor. Mauris vel interdum lacus. In ut tellus odio. Aliquam mattis mi at nisl elementum consequat. Sed odio purus, imperdiet sit amet enim nec, pretium mollis tellus. Pellentesque vitae tincidunt sapien. Curabitur faucibus euismod nibh, vitae elementum elit malesuada quis. Etiam ut turpis vel dui varius dapibus. Duis at tempus nisi, sit amet luctus orci. Integer porta sapien at purus mattis tempus. Aenean sagittis libero nisi, pharetra consectetur sem hendrerit sit amet.<br/>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam aliquet lacus at neque interdum malesuada. Sed finibus vestibulum velit, in semper arcu vehicula eget. Nunc tincidunt nunc risus, id volutpat sem lobortis vel. Maecenas facilisis leo et faucibus viverra. Nulla commodo nulla velit, eget eleifend ipsum vehicula a. Morbi mattis vitae nibh ut vulputate. Vestibulum blandit ullamcorper felis, at condimentum purus rutrum quis. Suspendisse semper, lacus et efficitur varius, lectus enim tincidunt nisl, a tempor massa ex sed odio. Sed id maximus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; <br/>

Sed mollis lectus nec sapien cursus, vel pharetra magna imperdiet. Ut egestas vel turpis id congue. Donec ornare aliquam erat, sit amet suscipit elit. Fusce auctor mi lacinia luctus auctor. Suspendisse elementum ipsum ut nunc fermentum, et luctus ex iaculis. Integer quis hendrerit massa, sollicitudin dictum nisi. Sed in nisi iaculis, mollis justo a, tincidunt libero. In id nunc ac mi vulputate porttitor nec condimentum ex. Mauris mattis convallis augue et semper. Aliquam blandit facilisis mi eget accumsan. Morbi fermentum facilisis dui, vitae sagittis neque gravida nec. Fusce facilisis tellus sagittis pulvinar iaculis. Nam vulputate, tellus vitae consectetur bibendum, leo lorem varius lectus, sit amet egestas nunc est ac dui. Donec lacus tortor, vestibulum et laoreet laoreet, dictum nec sapien. Nam mi eros, pharetra ut arcu sed, ornare iaculis elit.<br/>

Mauris porta felis vel eros condimentum posuere. Nulla eleifend luctus dolor a maximus. Proin vulputate tortor tellus, a molestie turpis laoreet at. Duis id nunc ante. Curabitur mollis placerat lacus et finibus. Nunc porttitor fringilla dolor id laoreet. Sed mauris tortor, condimentum at lorem in, faucibus efficitur dolor.<br/>

Aenean auctor nisi scelerisque tellus tincidunt aliquet. In faucibus metus nec ultricies condimentum. Sed tincidunt risus nibh, sed aliquam ex pretium ut. Integer blandit metus at dui ultricies, ut facilisis libero facilisis. Nam sagittis varius pellentesque. Morbi sagittis lacus ac sollicitudin rutrum. Vivamus leo massa, placerat ut tortor in, molestie condimentum elit. Vivamus rhoncus felis non pharetra molestie. Cras sodales dictum dapibus.<br/>

In euismod vestibulum quam, ut ultrices magna porttitor in. Fusce vitae luctus mi, ac varius velit. In bibendum, nunc maximus condimentum maximus, magna mi eleifend massa, sagittis rhoncus purus turpis quis ipsum. Donec consectetur feugiat risus. Proin nibh augue, facilisis at nulla ut, fermentum cursus dolor. Mauris vel interdum lacus. In ut tellus odio. Aliquam mattis mi at nisl elementum consequat. Sed odio purus, imperdiet sit amet enim nec, pretium mollis tellus. Pellentesque vitae tincidunt sapien. Curabitur faucibus euismod nibh, vitae elementum elit malesuada quis. Etiam ut turpis vel dui varius dapibus. Duis at tempus nisi, sit amet luctus orci. Integer porta sapien at purus mattis tempus. Aenean sagittis libero nisi, pharetra consectetur sem hendrerit sit amet.<br/>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam aliquet lacus at neque interdum malesuada. Sed finibus vestibulum velit, in semper arcu vehicula eget. Nunc tincidunt nunc risus, id volutpat sem lobortis vel. Maecenas facilisis leo et faucibus viverra. Nulla commodo nulla velit, eget eleifend ipsum vehicula a. Morbi mattis vitae nibh ut vulputate. Vestibulum blandit ullamcorper felis, at condimentum purus rutrum quis. Suspendisse semper, lacus et efficitur varius, lectus enim tincidunt nisl, a tempor massa ex sed odio. Sed id maximus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; <br/>

Sed mollis lectus nec sapien cursus, vel pharetra magna imperdiet. Ut egestas vel turpis id congue. Donec ornare aliquam erat, sit amet suscipit elit. Fusce auctor mi lacinia luctus auctor. Suspendisse elementum ipsum ut nunc fermentum, et luctus ex iaculis. Integer quis hendrerit massa, sollicitudin dictum nisi. Sed in nisi iaculis, mollis justo a, tincidunt libero. In id nunc ac mi vulputate porttitor nec condimentum ex. Mauris mattis convallis augue et semper. Aliquam blandit facilisis mi eget accumsan. Morbi fermentum facilisis dui, vitae sagittis neque gravida nec. Fusce facilisis tellus sagittis pulvinar iaculis. Nam vulputate, tellus vitae consectetur bibendum, leo lorem varius lectus, sit amet egestas nunc est ac dui. Donec lacus tortor, vestibulum et laoreet laoreet, dictum nec sapien. Nam mi eros, pharetra ut arcu sed, ornare iaculis elit.<br/>

Mauris porta felis vel eros condimentum posuere. Nulla eleifend luctus dolor a maximus. Proin vulputate tortor tellus, a molestie turpis laoreet at. Duis id nunc ante. Curabitur mollis placerat lacus et finibus. Nunc porttitor fringilla dolor id laoreet. Sed mauris tortor, condimentum at lorem in, faucibus efficitur dolor.<br/>

Aenean auctor nisi scelerisque tellus tincidunt aliquet. In faucibus metus nec ultricies condimentum. Sed tincidunt risus nibh, sed aliquam ex pretium ut. Integer blandit metus at dui ultricies, ut facilisis libero facilisis. Nam sagittis varius pellentesque. Morbi sagittis lacus ac sollicitudin rutrum. Vivamus leo massa, placerat ut tortor in, molestie condimentum elit. Vivamus rhoncus felis non pharetra molestie. Cras sodales dictum dapibus.<br/>

In euismod vestibulum quam, ut ultrices magna porttitor in. Fusce vitae luctus mi, ac varius velit. In bibendum, nunc maximus condimentum maximus, magna mi eleifend massa, sagittis rhoncus purus turpis quis ipsum. Donec consectetur feugiat risus. Proin nibh augue, facilisis at nulla ut, fermentum cursus dolor. Mauris vel interdum lacus. In ut tellus odio. Aliquam mattis mi at nisl elementum consequat. Sed odio purus, imperdiet sit amet enim nec, pretium mollis tellus. Pellentesque vitae tincidunt sapien. Curabitur faucibus euismod nibh, vitae elementum elit malesuada quis. Etiam ut turpis vel dui varius dapibus. Duis at tempus nisi, sit amet luctus orci. Integer porta sapien at purus mattis tempus. Aenean sagittis libero nisi, pharetra consectetur sem hendrerit sit amet.<br/></div>
        </div>
    )
}
