export const ActionTypes = {
    SET_IS_LOGGED: "SET_IS_LOGGED",
    SET_DESIRED_PATH: "SET_DESIRED_PATH",
    SET_CATEGORIES_PATH_MAP: "SET_CATEGORIES_PATH_MAP",
    SET_USER_ID: "SET_USER_ID",
    SET_SEARCH_PHRASE: "SET_SEARCH_PHRASE",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    CHANGE_QUANTITY_IN_CART: "CHANGE_QUANTITY_IN_CART"
}